// Code generated by mockery v1.0.0. DO NOT EDIT.

// GENERATED CODE: Do not edit.
// Configure in 'godel/config/mockery.yml' and regenerate with './godelw mockery'.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ChoriaKeycloakOidcEchoServiceClient is an autogenerated mock type for the ChoriaKeycloakOidcEchoServiceClient type
type ChoriaKeycloakOidcEchoServiceClient struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, inputArg
func (_m *ChoriaKeycloakOidcEchoServiceClient) Get(ctx context.Context, inputArg string) (string, error) {
	ret := _m.Called(ctx, inputArg)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, inputArg)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, inputArg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
