// Code generated by mockery v1.0.0. DO NOT EDIT.

// GENERATED CODE: Do not edit.
// Configure in 'godel/config/mockery.yml' and regenerate with './godelw mockery'.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ChoriaKeycloakOidcDictServiceClient is an autogenerated mock type for the ChoriaKeycloakOidcDictServiceClient type
type ChoriaKeycloakOidcDictServiceClient struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, inputArg
func (_m *ChoriaKeycloakOidcDictServiceClient) Delete(ctx context.Context, inputArg string) error {
	ret := _m.Called(ctx, inputArg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, inputArg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, inputArg
func (_m *ChoriaKeycloakOidcDictServiceClient) Get(ctx context.Context, inputArg string) (bool, error) {
	ret := _m.Called(ctx, inputArg)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, inputArg)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, inputArg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Put provides a mock function with given fields: ctx, inputArg
func (_m *ChoriaKeycloakOidcDictServiceClient) Put(ctx context.Context, inputArg string) error {
	ret := _m.Called(ctx, inputArg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, inputArg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
